export const allErrors = {
    REQUIRED: 'ERROR_REQUIRED',
    MIN: 'ERROR_MIN',
    MAX: 'ERROR_MAX',
    MIN_LENGTH: 'ERROR_MIN_LENGTH',
    MAX_LENGTH: 'ERROR_MAX_LENGTH',
    INVALID_EMAIL: 'ERROR_INVALID_EMAIL',
    CANNOT_BE_NEGATIVE: 'PRICE_CANNOT_BE_NEGATIVE',
    CANNOT_BE_ZERO: 'PRICE_CANNOT_BE_ZERO',
    INVALID_NUMBER_ERROR: 'INVALID_NUMBER_ERROR',
};
export default allErrors;
//# sourceMappingURL=allErrors.js.map