export const allErrors = {
    REQUIRED: 'ERROR_REQUIRED',
    MIN: 'ERROR_MIN',
    MAX: 'ERROR_MAX',
    INVALID_EMAIL: 'ERROR_INVALID_EMAIL',
    INVALID_NUMBER_ERROR: 'INVALID_NUMBER_ERROR',
    INVALID_DATE_ERROR: 'INVALID_DATE_ERROR'
};

export default allErrors;
